# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest
    # env:
    #   VARS: ${{vars.VARS}}

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create Environment
      uses: mkyai/env-builder@v1.0.1
      with:
        secrets: ${{ toJson(secrets) }}
        variables: ${{ toJson(vars) }}
    - run: docker build -t dev .
  deploy:
    environment: dev
    name: 'deploy'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Deploy image
        run: docker run dev
    
