name: Delete stand container
on:
  pull_request:
    types:
      - closed
    branches:
      - master
      - dev

env:
  STAND_NAME: ${{github.ref_name}}

jobs:
  closed:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.closed == true
    steps:
      - uses: actions/checkout@v4
      - name: on closed
        run: |

  merged:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - name: on merged
        run: |
          echo ${{github.ref_name}}
          echo ${{github.base_ref}}